source "http://rubygems.org"

gem 'uglifier'
gem 'colorize'

# Uncomment these two lines to use the less-js-source gem.
# Note that the gem is likely very old and won't support relative
# @import paths properly. In my case, the gem used lessjs 1.2.1, when
# the current stable release is 1.3.0.
# The alternative is to use NodeJS along with the js source downloaded
# directly from GitHub.
#gem 'execjs'
#gem 'less-js-source'

group :development do
end

group :test do
	gem 'test-unit'
end