// Generated by CoffeeScript 1.6.2
(function() {
  var SOME_FRAMEWORK;

  SOME_FRAMEWORK = {
    version: '0.0.1',
    toUpper: function(s) {
      'use strict';      return s.toUpperCase();
    }
  };

}).call(this);
